version: '3.0'
networks:
  backend:
    driver: bridge
services:
  mysql:
    image: mysql:8.0
    container_name: mysql8
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=root
    command:
      - "--default-authentication-plugin=mysql_native_password"
    privileged: true
    volumes:
      - "./data/mysql:/var/lib/mysql"
      - "./script/mysql/:/docker-entrypoint-initdb.d/"
    ports:
      - "13316:3306"
    networks:
      - backend
    restart: always

  redis:
    image: redis:7.0
    environment:
      - TZ=Asia/Shanghai
    privileged: true
    volumes:
      - "./data/redis:/data"
    ports:
      - "7379:6379"                          # 设置容器6379端口映射指定宿主机端口
    networks:
      - backend
    restart: always

  etcd:
    image: "bitnami/etcd:latest"
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      - "12379:2379"

  mongo:
    image: mongo:6.0
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    ports:
      - 27017:27017


  # 早期版本需要一个额外的 zookeeper 高版本已经不需要了
  kafka:
    image: 'bitnami/kafka:3.6.0'
    ports:
      - '9092:9092'
      - '9094:9094'
    environment:
      - KAFKA_CFG_NODE_ID=0
      # - 允许自动创建 topic，线上不要开启
      # 过多的 topic 会影响 broker 性能
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      # EXTERNAL 允许外部连接，使用 9094 端口
      # PLAINTEXT 内部连接使用 9092 端口
      - KAFKA_CFG_LISTENERS=PLAINTEXT://0.0.0.0:9092,CONTROLLER://:9093,EXTERNAL://0.0.0.0:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
  
  prometheus:
    image: prom/prometheus:v2.47.2
    volumes:
      - ./script/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  zipkin:
    # 这个镜像是不支持kafka之类的简化版本
    image: openzipkin/zipkin-slim:2.24
    ports:
      - "9411:9411"