apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv

spec:
  storageClassName: mysql-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/mysql
  