// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/wx-up/go-book/internal/repository"
	"github.com/wx-up/go-book/internal/repository/cache"
	"github.com/wx-up/go-book/internal/repository/dao"
	"github.com/wx-up/go-book/internal/service"
	"github.com/wx-up/go-book/internal/service/code"
	"github.com/wx-up/go-book/internal/web"
	"github.com/wx-up/go-book/ioc"
)

// Injectors from wire.go:

func InitWebService() *gin.Engine {
	db := ioc.CreateMysql()
	userDAO := dao.NewUserDAO(db)
	cmdable := ioc.CreateRedis()
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDAO, userCache)
	userService := service.NewUserService(userRepository)
	smsService := ioc.CreateSMSService()
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsCodeService := code.NewSmsCodeService(smsService, codeRepository)
	userHandler := web.NewUserHandler(userService, smsCodeService)
	v := ioc.CreateMiddlewares(cmdable)
	engine := ioc.InitWeb(userHandler, v)
	return engine
}
